### ISSUE TITLE
Use custom swaylock command

### ISSUE THREAD

**Issue by zabihexes** [loserMcloser/waylogout#11]
Is it possible to configure how swaylock is called?
I would like to execute something like this.

```bash
swaylock -F -i ~/Pictures/Wallpapers/AlphaCoder/StrangerThings/1258898.jpg --effect-blur 10x5 --clock --indicator
```

**Comment by loserMcloser** [comment]
Yes, you can use any lock command you like, it doesn't even have to be `swaylock`. If you look at the example `waylogout` config on the main project page, you will see option `--lock-command="echo lock"` as a "dummy" lock command just for demonstration purposes. So you would want to use option `--lock-command="swaylock -F -i ~/Pictures/Wallpapers/AlphaCoder/StrangerThings/1258898.jpg --effect-blur 10x5 --clock --indicator"`.

Alternatively, you could just juse `--lock-command=swaylock` and put all your swaylock options in `$XDG_CONFIG_HOME/swaylock/config` --- see `man swaylock` for more info on configuring swaylock via a config file.
