### ISSUE TITLE
New feature: preselect default_action

### ISSUE THREAD

**Issue by alteriks** [loserMcloser/waylogout#12]
Hi, thanks for a great logout screen.
Would you be so kind and add new feature to preselect one of the configured actions?
I've found myself to use suspend the most, but I'd like to still confirm this with hitting enter.
Maybe you could add config `default_action` or even piping to waylogout would be nice ie 
```bash 
echo s | waylogout 
```

**Comment by loserMcloser** [comment]
`default-action` config option added in f90e1b8

**Comment by alteriks** [comment]
@loserMcloser Thank you for your fast reaction! Waylogout works perfectly!
