### ISSUE TITLE
Does not show buttons

### ISSUE THREAD

**Issue by kiesel** [loserMcloser/waylogout#15]
I noticed that waylogout does not show any buttons on my laptop. When connected to external monitor it works, though.

It just shows the configured fade-out effect but no buttons.

**Comment by loserMcloser** [comment]
That's weird, not sure what the cause could be. Works fine on my laptop. Do you use swaylock-effects? Does that show the indicator on your laptop's main display?

**Comment by kiesel** [comment]
Nope, sorry, don't use that.

However, I tried something. So these are the displays:

```
$ swaymsg -t get_outputs
Output DP-5 'Samsung Electric Company LU28R55 H4ZR306533' (focused)
  Current mode: 3840x2160 @ 60.000 Hz
  Position: 1280,0
  Scale factor: 2.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 3: ‭‬ ‭‬ 
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    [...]

Output eDP-1 'Japan Display Inc. 0x0000 Unknown' (inactive)
  Available modes:
    2560x1440 @ 59.998 Hz
```

The laptop display is at 2560x1440 with scale 2.0 - so effective resolution would be 1280x720. I have this config:

```
$ head -n 7 .config/waylogout/config
fade-in=2
poweroff-command="systemctl poweroff"
suspend-command="systemctl suspend"
reboot-command="systemctl reboot"
logout-command="swaymsg exit"
lock-command="swaylock"
default-action="lock"
```

Maybe these don't all fit into that screen resolution? When I remove 2 labels, they then show up.

**Comment by loserMcloser** [comment]
Sorry for taking so long to reply, very busy at work. ;)

To test if it's an issue of not fitting within the screen size: try adjusting sizing options like `--indicator-radius` and `--indicator-separation` and/or try commenting out some of the actions in your config so that there are only one or two actions enabled.

**Comment by kiesel** [comment]
The key is the `--indicator-separation` flag - when that is set, the buttons will render (even if the whole line is too wide for the display, they show up).

Works for me now, feel free to close (or fix it somehow).
