### ISSUE TITLE
Keyboard shortcuts and a config file

### ISSUE THREAD

**Issue by milkbu** [loserMcloser/waylogout#2]
I'm very impressed with this solution -- and it really is a hidden gem, so I've just added to the "useful add ons" on the Sway wiki. The only thing that would make it better are keyboard shortcuts, like l to lock, e to logout, s to suspend, etc. I mean, ideally it could be remappable, but I would be more than happy with the usual ones. And oh, I'm not sure if waylogout supports config files, I haven't seen a mention on the page but it would be great as well, since swaylock does supports it.

**Comment by loserMcloser** [comment]
Thanks for the kind words.

Config files are supported, check out `man waylogout`

There are default keyboard shortcuts, not sure if they're the "usual" ones, but again check out the NAVIGATION and SHORTCUT KEYS sections in the man page. Re-mapping shortcut keys through the config or command line should be easy to implement, but won't get to it until winter break.

**Comment by loserMcloser** [comment]
b5afe02
