### ISSUE TITLE
rectangles instead symbols

### ISSUE THREAD

**Issue by 532910** [loserMcloser/waylogout#5]
I see just rectangles instead symbols.
`font=FontAwesome`
sway 1.7-6
debian sid

swaylock with
```
font=FontAwesome
datestr=
```
show power off symbol successfully

**Comment by loserMcloser** [comment]
This project uses the `font` setting for the text font, FontAwesome is used for symbols automatically.

Does [example command](https://github.com/loserMcloser/waylogout#example-command) work for you?

**Comment by 532910** [comment]
![IMG_20230130_132851](https://user-images.githubusercontent.com/14617699/215448202-f607f08a-f602-453e-8f4d-8e178dd5aca3.jpg)

**Comment by loserMcloser** [comment]
What version of FontAwesome are you using? This project requires FontAwesome 6 Free, but all I see in Debian Sid is [fonts-font-awesome (5.0.10+really4.7.0~dfsg-4.1)](https://packages.debian.org/sid/fonts-font-awesome), and the page for that package says

> Please note that this package provides Font Awesome 4 (not Font Awesome 5 or Font Awesome 6 which are different fonts with different licensing).

**Comment by 532910** [comment]
I have copied a power symbol from the [main.c](https://github.com/loserMcloser/waylogout/blob/f8a07e2fc8c43d8f8dc5c6a36df65bd3c29bc849/main.c#L1359) and put in swaylock config, and it shows it successfully using Font Awesome from debian, thus I believe the issue is not in the debian font.

**Comment by 532910** [comment]
OK. I have [downloaded v4](https://fontawesome.com/v4/assets/font-awesome-4.7.0.zip) and put  `fontawesome-webfont.ttf` and `FontAwesome.otf` to `~/.local/share/fonts`, fc-list see them:
```
% fc-list | grep -i aweso
/usr/share/fonts/opentype/font-awesome/FontAwesome.otf: FontAwesome:style=Regular
/home/sergio/.local/share/fonts/fontawesome-webfont.ttf: FontAwesome:style=Regular
/usr/share/fonts/truetype/font-awesome/fontawesome-webfont.ttf: FontAwesome:style=Regular
/home/sergio/.local/share/fonts/FontAwesome.otf: FontAwesome:style=Regular
```
but waylogout still shows rectangles

**Comment by 532910** [comment]
Moreover, debian package version is `5.0.10+really4.7.0~dfsg-4.1`, that means it's `4.7` really.

**Comment by loserMcloser** [comment]
I had the font name for Font Awesome hardcoded to "Font Awesome 6 Free" but I've now added an option (`fa-font`) to specify the name for your Font Awesome font.

So try updating your git repo for `waylogout` to the latest commit (291c70b), rebuilding, and then running with option `--fa-font="FontAwesome"` which should match the name of your Font Awesome package on Debian.

**Comment by 532910** [comment]
Awesome! Thank you!
