### ISSUE TITLE
please add support for custom actions

### ISSUE THREAD

**Issue by 532910** [loserMcloser/waylogout#7]
like custom icons and custom labels

**Comment by loserMcloser** [comment]
This project is focussed on power/login management. Is there some particular action related to power/login management which you would like added to the menu of options? Or you want to change the language of the labels? Or something else?

**Comment by 532910** [comment]
I want to reload sway config, change cpu governor, change actions order ...

**Comment by loserMcloser** [comment]
The actions will appear on the screen in the order that you list the `*-command` options in the config file.

I've added a 'reload' action, see fb0850b.

Changing cpu governor sounds like something you should bind a shortcut key to bring up a menu program (wofi or whatever) to do. Or bind a shortcut key to a script that will cycle through some list of governors, and pop up a notification telling you what the current governor is.

**Comment by 532910** [comment]
Just two-three actions for two-three governors, without popups or menus.

**Comment by 532910** [comment]
> The actions will appear on the screen in the order that you list the *-command options in the config file.

Nice! Could you describe this in the readme please.

**Comment by loserMcloser** [comment]
> > The actions will appear on the screen in the order that you list the *-command options in the config file.
> 
> Nice! Could you describe this in the readme please.

This is already described in the `APPEARANCE` section of the manpage.

**Comment by loserMcloser** [comment]
> Just two-three actions for two-three governors, without popups or menus.

Your screen real estate will get crowded --- currently there is no code to arrange the action indicators in more than a single horizontal row. So there is a fair bit of complexity needed to be added to handle both reading custom actions from the config and also adding and handling an `nrows` config option.

I will mark this as a feature request, but I likely will not have any time to work on it until the summer, if then.

Pull requests welcome.
