### ISSUE TITLE
pointer activity area not aligned with visual

### ISSUE THREAD

**Issue by 532910** [loserMcloser/waylogout#9]
https://user-images.githubusercontent.com/14617699/216922551-afb05403-fe02-4d11-a8c2-47b73b7859b7.mp4

**Comment by loserMcloser** [comment]
When you post a screenshot or video, can you please include the command/config you are using? The example command in the README does not exhibit this behaviour on my system, so it's difficult for me to debug if I can't reproduce the bug.

**Comment by 532910** [comment]
Sorry for delay, but I'm unable to reproduce this ):
I'll reopen this issue if I'll found config.
